<?php

/**
 * The plugin bootstrap file
 *
 * This file is read by WordPress to generate the plugin information in the plugin
 * admin area. This file also includes all of the dependencies used by the plugin,
 * registers the activation and deactivation functions, and defines a function
 * that starts the plugin.
 *
 * @link              https://www.linkedin.com/in/syed-ali-haider-a35366194/
 * @since             1.0.0
 * @package           Football_League_Data
 *
 * @wordpress-plugin
 * Plugin Name:       Football League Data
 * Plugin URI:        https://umairabid.tk/Football League Data
 * Description:       This is a short description of what the plugin does. It's displayed in the WordPress admin area.
 * Version:           1.0.0
 * Author:            Syed Ali Haider
 * Author URI:        https://www.linkedin.com/in/syed-ali-haider-a35366194/
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       football-league-data
 * Domain Path:       /datatv
 */

// If this file is called directly, abort.
if (!defined('WPINC')) {
    die;
}

/**
 * Currently plugin version.
 * Start at version 1.0.0 and use SemVer - https://semver.org
 * Rename this for your plugin and update it as you release new versions.
 */
define('FOOTBALL_LEAGUE_DATA_VERSION', '1.0.0');

/**
 * The code that runs during plugin activation.
 * This action is documented in includes/class-football-league-data-activator.php
 */
function activate_football_league_data()
{
    require_once plugin_dir_path(__FILE__) . 'includes/class-football-league-data-activator.php';
    Football_League_Data_Activator::activate();
}

/**
 * The code that runs during plugin deactivation.
 * This action is documented in includes/class-football-league-data-deactivator.php
 */
function deactivate_football_league_data()
{
    require_once plugin_dir_path(__FILE__) . 'includes/class-football-league-data-deactivator.php';
    Football_League_Data_Deactivator::deactivate();
}

register_activation_hook(__FILE__, 'activate_football_league_data');
register_deactivation_hook(__FILE__, 'deactivate_football_league_data');

/**
 * The core plugin class that is used to define internationalization,
 * admin-specific hooks, and public-facing site hooks.
 */
require plugin_dir_path(__FILE__) . 'includes/class-football-league-data.php';

/**
 * Begins execution of the plugin.
 *
 * Since everything within the plugin is registered via hooks,
 * then kicking off the plugin from this point in the file does
 * not affect the page life cycle.
 *
 * @since    1.0.0
 */

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class FootballLeagueData
{
    private $football_league_data_options;

    public function __construct()
    {
        add_action('admin_menu', array($this, 'football_league_data_add_plugin_page'));
        add_action('admin_init', array($this, 'football_league_data_page_init'));
    }

    public function football_league_data_add_plugin_page()
    {
        add_options_page(
            'Football League Data', // page_title
            'Football League Data', // menu_title
            'manage_options', // capability
            'football-league-data', // menu_slug
            array($this, 'football_league_data_create_admin_page') // function
        );
    }

    public function football_league_data_create_admin_page()
    {
        $this->football_league_data_options = get_option('football_league_data_option_name'); ?>

        <div class="wrap">
            <h2>Football League Data</h2>
            <p>Football League Data - Settings</p>
            <?php
            $football_league_data_options = get_option('football_league_data_option_name'); // Array of All Options


            $db_host_0 = $football_league_data_options['db_host_0']; // DB Host
            $db_name_1 = $football_league_data_options['db_name_1']; // DB Name
            $db_user_2 = $football_league_data_options['db_user_2']; // DB User
            $db_pass_3 = $football_league_data_options['db_pass_3']; // DB Pass


            $conn = mysqli_connect($db_host_0, $db_user_2, $db_pass_3,  $db_name_1);

            if ($conn) {


            ?> <h1>Connection Status - <span style="color: green;">Connected</span></h1>

            <?php  } else {

            ?>
                <h1>Connection Status - <span style="color: red;">Lost</span></h1>

            <?php } ?>

            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields('football_league_data_option_group');
                do_settings_sections('football-league-data-admin');
                submit_button();
                ?>
            </form>
        </div>
<?php }

    public function football_league_data_page_init()
    {
        register_setting(
            'football_league_data_option_group', // option_group
            'football_league_data_option_name', // option_name
            array($this, 'football_league_data_sanitize') // sanitize_callback
        );

        add_settings_section(
            'football_league_data_setting_section', // id
            'Settings', // title
            array($this, 'football_league_data_section_info'), // callback
            'football-league-data-admin' // page
        );

        add_settings_field(
            'db_host_0', // id
            'DB Host', // title
            array($this, 'db_host_0_callback_data'), // callback
            'football-league-data-admin', // page
            'football_league_data_setting_section' // section
        );

        add_settings_field(
            'db_name_1', // id
            'DB Name', // title
            array($this, 'db_name_1_callback_data'), // callback
            'football-league-data-admin', // page
            'football_league_data_setting_section' // section
        );

        add_settings_field(
            'db_user_2', // id
            'DB User', // title
            array($this, 'db_user_2_callback_data'), // callback
            'football-league-data-admin', // page
            'football_league_data_setting_section' // section
        );

        add_settings_field(
            'db_pass_3', // id
            'DB Pass', // title
            array($this, 'db_pass_3_callback_data'), // callback
            'football-league-data-admin', // page
            'football_league_data_setting_section' // section
        );
    }

    public function football_league_data_sanitize($input)
    {
        $sanitary_values = array();
        if (isset($input['db_host_0'])) {
            $sanitary_values['db_host_0'] = sanitize_text_field($input['db_host_0']);
        }

        if (isset($input['db_name_1'])) {
            $sanitary_values['db_name_1'] = sanitize_text_field($input['db_name_1']);
        }

        if (isset($input['db_user_2'])) {
            $sanitary_values['db_user_2'] = sanitize_text_field($input['db_user_2']);
        }

        if (isset($input['db_pass_3'])) {
            $sanitary_values['db_pass_3'] = sanitize_text_field($input['db_pass_3']);
        }

        return $sanitary_values;
    }

    public function football_league_data_section_info()
    {
    }

    public function db_host_0_callback_data()
    {
        printf(
            '<input class="regular-text" type="text" name="football_league_data_option_name[db_host_0]" id="db_host_0" value="%s">',
            isset($this->football_league_data_options['db_host_0']) ? esc_attr($this->football_league_data_options['db_host_0']) : ''
        );
    }

    public function db_name_1_callback_data()
    {
        printf(
            '<input class="regular-text" type="text" name="football_league_data_option_name[db_name_1]" id="db_name_1" value="%s">',
            isset($this->football_league_data_options['db_name_1']) ? esc_attr($this->football_league_data_options['db_name_1']) : ''
        );
    }

    public function db_user_2_callback_data()
    {
        printf(
            '<input class="regular-text" type="text" name="football_league_data_option_name[db_user_2]" id="db_user_2" value="%s">',
            isset($this->football_league_data_options['db_user_2']) ? esc_attr($this->football_league_data_options['db_user_2']) : ''
        );
    }

    public function db_pass_3_callback_data()
    {
        printf(
            '<input class="regular-text" type="text" name="football_league_data_option_name[db_pass_3]" id="db_pass_3" value="%s">',
            isset($this->football_league_data_options['db_pass_3']) ? esc_attr($this->football_league_data_options['db_pass_3']) : ''
        );
    }
}
if (is_admin())
    $FLDoptions = new FootballLeagueData();


add_action('wp_head', 'myplugin_ajaxurl_2');

function myplugin_ajaxurl_2()
{

    echo '<script type="text/javascript">
           var ajaxurl = "' . admin_url('admin-ajax.php') . '";
         </script>';
}

add_action('wp_ajax_my_action', 'my_action');
add_action('wp_ajax_nopriv_my_action', 'my_action');



function dbConnect()
{

    $football_league_data_options = get_option('football_league_data_option_name'); // Array of All Options
    $db_host_0 = $football_league_data_options['db_host_0']; // DB Host
    $db_name_1 = $football_league_data_options['db_name_1']; // DB Name
    $db_user_2 = $football_league_data_options['db_user_2']; // DB User
    $db_pass_3 = $football_league_data_options['db_pass_3']; // DB Pass
    return $connection = mysqli_connect($db_host_0, $db_user_2, $db_pass_3, $db_name_1);
}


function my_action()
{

    // global $wpdb; // this is how you get access to the database

    //     $whatever = intval( $_POST['whatever'] );

    //     $whatever += 10;

    //         echo $whatever;

    //     die(); // this is required to terminate immediately and return a proper response

    $country = $_POST['country'];
    $team = $_POST['team'];
    $date = $_POST['date'];
    $league = $_POST['league'];
    $l_country = $_POST['l_country'];

    $connection = dbConnect();
    $connection->set_charset("utf8mb4");
    if ($connection) {

        if ($country != "none") {
            $q = "SELECT `idEvent` FROM `tv_thesportsdb` WHERE `dateEvent` = '$date' AND `strCountry`= '$country' GROUP BY `idEvent` ORDER BY `idEvent` ASC";
            $result = mysqli_query($connection, $q);
            $num_rows = mysqli_num_rows($result);
        } else {
            $q = "SELECT `idEvent` FROM `tv_thesportsdb` WHERE `dateEvent` = '$date' GROUP BY `idEvent` ORDER BY `idEvent` ASC";
            $result = mysqli_query($connection, $q);
            $num_rows = mysqli_num_rows($result);
        }

        if ($num_rows > 0) {
            $dataArray = array();
            $dataArray["league"] = array();
            $dataArray["allleagues"] = array();
            $dataArray["countries"] = array();
            for ($i = 0; $i < $num_rows; $i++) {
                mysqli_data_seek($result, $i);
                $row = mysqli_fetch_row($result);
                $idEvent_tv = $row[0];

                $q1 = "SELECT `idAPIfootball` FROM `fixtures_thesportsdb` WHERE `idEvent` = '$idEvent_tv' ORDER BY `idEvent` ASC limit 1";
                $result_1 = mysqli_query($connection, $q1);
                $array_1 = mysqli_fetch_array($result_1);

                if ($array_1 == NULL) {
                } else {
                    $idAPIfootball_spdb = $array_1['idAPIfootball'];

                    if ($team != "none") {
                        if ($league != "none" && $l_country != "none") {
                            $q2 = "SELECT `league_id`, `status_short`, `goals_home`, `goals_away`, `fixture_date`, `league_logo`, `league_name`, `league_country`,`teams_home_name`, `teams_home_logo`, `teams_away_name`, `teams_away_logo` FROM `fixtures` 
                                WHERE `fixture_id` = '$idAPIfootball_spdb' AND ( (`teams_home_name` LIKE '$team%' || `teams_home_name` = '$team') || (`teams_away_name` LIKE '$team%'|| `teams_away_name` = '$team' ) ) AND `league_name` = '$league' AND `league_country` = '$l_country' order by `fixture_id` ASC limit 1";
                            $result_2 = mysqli_query($connection, $q2);
                            $array_2 = mysqli_fetch_array($result_2);
                        } else {
                            $q2 = "SELECT `league_id`, `status_short`, `goals_home`, `goals_away`, `fixture_date`, `league_logo`, `league_name`, `league_country`,`teams_home_name`, `teams_home_logo`, `teams_away_name`, `teams_away_logo` FROM `fixtures` 
                                WHERE `fixture_id` = '$idAPIfootball_spdb' AND ( (`teams_home_name` LIKE '$team%' || `teams_home_name` = '$team') || (`teams_away_name` LIKE '$team%'|| `teams_away_name` = '$team' ) ) order by `fixture_id` ASC limit 1";
                            $result_2 = mysqli_query($connection, $q2);
                            $array_2 = mysqli_fetch_array($result_2);
                        }
                    } else {
                        if ($league != "none" && $l_country != "none") {
                            $q2 = "SELECT `league_id`, `status_short`, `goals_home`, `goals_away`, `fixture_date`, `league_logo`, `league_name`, `league_country`, `teams_home_name`, `teams_home_logo`, `teams_away_name`, `teams_away_logo` FROM `fixtures` WHERE `fixture_id` = '$idAPIfootball_spdb' AND `league_name` = '$league' AND `league_country` = '$l_country' order by `fixture_id` ASC limit 1";
                            $result_2 = mysqli_query($connection, $q2);
                            $array_2 = mysqli_fetch_array($result_2);
                        } else {
                            $q2 = "SELECT `league_id`, `status_short`, `goals_home`, `goals_away`, `fixture_date`, `league_logo`, `league_name`, `league_country`, `teams_home_name`, `teams_home_logo`, `teams_away_name`, `teams_away_logo` FROM `fixtures` WHERE `fixture_id` = '$idAPIfootball_spdb' order by `fixture_id` ASC limit 1";
                            $result_2 = mysqli_query($connection, $q2);
                            $array_2 = mysqli_fetch_array($result_2);
                        }
                    }


                    if ($array_2 == NULL) {
                    } else {
                        $league_id = $array_2['league_id'];
                        $goals_home = $array_2['goals_home'];
                        $goals_away = $array_2['goals_away'];
                        $fixture_date = $array_2['fixture_date'];
                        $league_logo = $array_2['league_logo'];
                        $league_name = $array_2['league_name'];
                        $league_country = $array_2['league_country'];
                        $teams_home_name = $array_2['teams_home_name'];
                        $teams_home_logo = $array_2['teams_home_logo'];
                        $teams_away_name = $array_2['teams_away_name'];
                        $teams_away_logo = $array_2['teams_away_logo'];
                        $status_short = $array_2['status_short'];

                        $time = date("H:i", strtotime($fixture_date));

                        if ($status_short != "FT") {

                            $goals_home = "-";
                            $goals_away = "-";
                        }



                        if ($time == "" || $fixture_date == "") {
                            $time = "00:00";
                        }

                        $eventdetails = array("league" =>  array(
                            "league_id" => $league_id,
                            "leaguetitle" => $league_country,
                            "leaguelogo" => $league_logo,
                            "leaguecountry" => $league_country,
                            "leaguename" => $league_name,
                            "teamhomelogo" => $teams_home_logo,
                            "teamhomelogotitle" => $teams_home_name,
                            "teamhomename" => $teams_home_name,
                            "teamhomegoal" => $goals_home,
                            "teamawaylogo" => $teams_away_logo,
                            "teamawaylogotitle" => $teams_away_name,
                            "teamawayname" => $teams_away_name,
                            "teamawaygoal" => $goals_away,
                            "time" => $time,
                        ));

                        $eventdetails["channels"] = array();
                        if ($country != "none") {
                            $q_4 = "SELECT * FROM `tv_thesportsdb` WHERE `dateEvent` = '$date' AND `idEvent` = '$idEvent_tv' AND (`strCountry` = 'world' OR `strCountry`= 'europe' OR `strCountry`= '$country') ";
                        } else {
                            $q_4 = "SELECT * FROM `tv_thesportsdb` WHERE `dateEvent` = '$date' and `idEvent` = '$idEvent_tv'";
                        }
                        $result_4 = mysqli_query($connection, $q_4);
                        if ($result_4) {

                            $num_rows_array = mysqli_num_rows($result_4);
                            for ($l = 0; $l < $num_rows_array; $l++) {
                                $row_2 = mysqli_fetch_row($result_4);
                                $channeldetails = array(
                                    "channeltitle" => $row_2[5],
                                    "channellogo" => $row_2[6],
                                    "channelname" => $row_2[7]
                                );
                                array_push($eventdetails["channels"], $channeldetails);
                            }
                            array_push($dataArray["league"], $eventdetails);
                        }
                    }
                }
            }

            // $q_98 = "SELECT `strCountry`,`idEvent` FROM `tv_thesportsdb` WHERE `dateEvent` = '$date' GROUP BY `strCountry` ORDER BY `idEvent` ASC";
            // $result_98 = mysqli_query($connection, $q_98);
            // $num_rows_98 = mysqli_num_rows($result_98);
            // if ($num_rows_98 > 0) {
            //     $countryArray = array();
            //     $j = 0;

            //     for ($i = 0; $i < $num_rows_98; $i++) {
            //         mysqli_data_seek($result_98, $i);
            //         $row = mysqli_fetch_row($result_98);

            //         $q_00 = "SELECT `idEvent`, `idAPIfootball` FROM `fixtures_thesportsdb` WHERE `idAPIfootball` =  '$row[1]' ORDER BY `idEvent` ASC limit 1";
            //         $result_1 = mysqli_query($connection, $q_00);
            //         $array_1 = mysqli_fetch_array($result_1);
            //         if ($array_1 == NULL) {
            //         } else {
            //             $idAPIfootball = $array_1['idAPIfootball'];

            //             $q_55 = "SELECT `fixture_id` FROM `fixtures` WHERE `fixture_id` =  '$idAPIfootball' ORDER BY `idEvent` ASC limit 1";
            //             $result_55 = mysqli_query($connection, $q_55);
            //             $array_55 = mysqli_fetch_array($result_55);
            //             if ($array_55 == NULL) {
            //             } else {
            //                 $fixture_id = $array_55['fixture_id'];

            //                 if ($fixture_id != "" || $fixture_id != 0) {
            //                     $countryArray[$j] = $row[0];
            //                     $j++;
            //                 }
            //             }
            //         }
            //     }
            //     sort($countryArray);
            // } else {
            //     $countryArray = NULL;
            // }

            $connection->set_charset("utf8mb4");
            $q_99 = "SELECT `fixture_id`, `league_name`,`league_country`,`league_logo` FROM `fixtures` WHERE `date` = '$date' ORDER BY 'league_country' ASC";
            $result_99 = mysqli_query($connection, $q_99);
            $num_rows_99 = mysqli_num_rows($result_99);
            if ($num_rows_99 > 0) {
                $leagueArray = array();
                $leagues = array();
                $k = 0;
                for ($f = 0; $f < $num_rows_99; $f++) {
                    mysqli_data_seek($result_99, $f);
                    $row_99 = mysqli_fetch_row($result_99);

                    $q_00 = "SELECT `idEvent` FROM `fixtures_thesportsdb` WHERE `idAPIfootball` =  '$row_99[0]' ORDER BY `idEvent` ASC limit 1";
                    $result_1 = mysqli_query($connection, $q_00);
                    $array_1 = mysqli_fetch_array($result_1);
                    if ($array_1 == NULL) {
                    } else {
                        $idEvent = $array_1['idEvent'];

                        $q_11 = "SELECT `idEvent` FROM `tv_thesportsdb` WHERE `idEvent` =  '$idEvent' AND `dateEvent` = '$date' ORDER BY `idEvent` ASC limit 1";
                        $result_11 = mysqli_query($connection, $q_11);
                        $array_11 = mysqli_fetch_array($result_11);
                        if ($array_11 == NULL) {
                        } else {
                            $idEvent_1 = $array_11['idEvent'];

                            if ($idEvent_1 != "" || $idEvent_1 != 0) {
                                $leagueArray[$k] = $row_99[2] . ' > ' . $row_99[1] . ' > ' . $row_99[3];
                                $k++;
                            }
                        }
                    }
                }
            } else {
                $leagueArray = NULL;
            }

            $leagueArray = array_unique($leagueArray);
            $country_leagues = array();
            $u = 0;
            foreach ($leagueArray as $value) {
                $country_leagues[$u] = $value;
                $u++;
            }
            // array_push($dataArray["tvcountries"], $countryArray);
            array_push($dataArray["allleagues"], $country_leagues);
            array_push($dataArray["l_countries"], $leagues);

            echo json_encode($dataArray);
        }
    } else {
        echo "DB Error";
    }

    die(); // this is required to terminate immediately and return a proper response

}


add_shortcode('DATATV', 'test_value_2');

function test_value_2($atts = [], $content = null, $tag = '')
{

    if ($atts['language'] != "") {
        $option = shortcode_atts(
            array(
                'language' => 'en',
                'country' => 'bulgaria',
                'league' => '44,343,343,3432'
            ),
            $atts,
            $tag
        );
        $language = $option['language'];
        $country = $option['country'];
        $league = $option['league'];
    }
    if ($atts['language'] == "") {

        $language = "";
        if ($language == "" || $language == 0 || $language == NULL) {
            $language = "en";
        }
    }

    if ($atts['country'] == "") {

        $country = "";
        if ($country == "" || $country == 0 || $country == NULL) {
            $country = "";
        }
    }

    if ($atts['league'] == "") {

        $league = "";
        if ($league == "" || $league == 0 || $league == NULL) {
            $league = "";
        }
    }

    // if ($atts['language'] != "") {
    //     $option = shortcode_atts(
    //         array(
    //             'language' => 'en'
    //         ),
    //         $atts,
    //         $tag
    //     );

    //     echo  $language = $option['language'];
    //     if ($language == "" || $language == NULL) {
    //         $language = "en";
    //     }
    //     echo  $language;
    // }
    include 'public/file-data.php';
    return $FLDview->views_2($language, $country, $league);
}
